name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build --if-present
          start: npm start --if-present
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60 # seconds
          command: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
